packages:
  - apps/*
  - packages/*
allowBuilds:
  better-sqlite3: true
  electron-winstaller: false
  esbuild: true
minimumReleaseAgeExclude:
  - electron@44.5.1
saveExact: true
strictPeerDependencies: true
