import { expect, test } from '@playwright/test';

test('guides first-time setup, saves settings and starts chatting without restarting', async ({ page }) => {
  await page.goto('http://127.0.0.1:4320');
  await expect(page.getByRole('heading', { name: '连接你的第一个模型' })).toBeVisible();
  await page.getByLabel('模型名称').fill('fixture-model');
  await page.getByLabel('API Key', { exact: false }).fill('fixture-key');
  await page.getByLabel('上下文窗口（tokens）').fill('65536');
  await page.getByLabel('最大输出（tokens）').fill('2048');
  await page.getByRole('button', { name: '保存并开始对话' }).click();
  await expect(page.getByRole('textbox', { name: '消息' })).toBeEnabled();
  await page.getByRole('textbox', { name: '消息' }).fill('你好');
  await page.getByRole('button', { name: '发送', exact: false }).click();
  await expect(page.getByText('这是第 1 轮回复。', { exact: false })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: '连接你的第一个模型' })).toHaveCount(0);
  await page.getByRole('button', { name: '模型设置', exact: true }).click();
  await expect(page.getByLabel('模型名称')).toHaveValue('fixture-model');
  await expect(page.getByLabel('上下文窗口（tokens）')).toHaveValue('65536');
  await expect(page.getByLabel('最大输出（tokens）')).toHaveValue('2048');
  await expect(page.getByLabel('API Key', { exact: false })).toHaveValue('');
  await page.getByLabel('最大输出（tokens）').fill('0');
  await page.getByLabel('模型名称').fill('updated-model');
  await page.getByRole('button', { name: '保存并开始对话' }).click();
  await expect(page.getByText('updated-model', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: '模型设置', exact: true }).click();
  await expect(page.getByLabel('最大输出（tokens）')).toHaveValue('0');
  await expect(page.getByLabel('API Key', { exact: false })).toHaveAttribute('placeholder', '留空保留当前密钥');
});
