import { expect, test } from '@playwright/test';

test('guides first-time setup, saves settings and starts chatting without restarting', async ({ page }) => {
  await page.goto('http://127.0.0.1:4320');
  await expect(page.getByRole('heading', { name: '连接你的第一个模型' })).toBeVisible();
  await page.getByLabel('模型名称').fill('fixture-model');
  await page.getByLabel('API Key', { exact: false }).fill('fixture-key');
  await page.getByLabel('API Key', { exact: false }).blur();
  await expect(page.getByLabel('上下文窗口（tokens）')).toHaveValue('32768');
  await expect(page.getByText('已从服务商读取窗口容量，可手动调整。')).toBeVisible();
  await page.getByLabel('上下文窗口（tokens）').fill('65536');
  await page.getByLabel('最大输出（tokens）').fill('2048');
  await page.getByRole('button', { name: '保存并开始对话' }).click();
  await expect(page.getByRole('textbox', { name: '消息' })).toBeEnabled();
  await page.getByRole('textbox', { name: '消息' }).fill('你好');
  await page.getByRole('button', { name: '发送', exact: false }).click();
  await expect(page.getByText('这是第 1 轮回复。', { exact: false })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: '连接你的第一个模型' })).toHaveCount(0);
  await page.getByRole('button', { name: '模型设置', exact: true }).click();
  await expect(page.getByLabel('模型名称')).toHaveValue('fixture-model');
  await expect(page.getByLabel('上下文窗口（tokens）')).toHaveValue('65536');
  await expect(page.getByLabel('最大输出（tokens）')).toHaveValue('2048');
  await expect(page.getByLabel('API Key', { exact: false })).toHaveValue('');
  await page.getByLabel('最大输出（tokens）').fill('0');
  await page.getByLabel('模型名称').fill('updated-model');
  await page.getByLabel('模型名称').blur();
  await expect(page.getByLabel('上下文窗口（tokens）')).toHaveValue('262144');
  await page.getByRole('button', { name: '保存并开始对话' }).click();
  await expect(page.getByText('updated-model', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: '模型设置', exact: true }).click();
  await expect(page.getByLabel('最大输出（tokens）')).toHaveValue('0');
  await expect(page.getByLabel('API Key', { exact: false })).toHaveAttribute('placeholder', '留空保留当前密钥');
  await page.getByLabel('模型名称').fill('unknown-model');
  await page.getByLabel('模型名称').blur();
  await expect(page.getByText('未能自动获取窗口容量，请按服务商规格手动填写。')).toBeVisible();
  await expect(page.getByLabel('上下文窗口（tokens）')).toHaveValue('');
  await page.getByRole('button', { name: '保存并开始对话' }).click();
  await expect(page.getByRole('alert')).toContainText('请填写模型的上下文窗口');
  await page.getByLabel('上下文窗口（tokens）').fill('1000000');
  await page.getByRole('button', { name: '保存并开始对话' }).click();
  await page.reload();
  await page.getByRole('button', { name: '模型设置', exact: true }).click();
  await expect(page.getByLabel('上下文窗口（tokens）')).toHaveValue('1000000');
  const requested = Promise.withResolvers<void>();
  const release = Promise.withResolvers<void>();
  await page.route('**/api/settings/model/context', async (route) => {
    requested.resolve();
    await release.promise;
    await route.fulfill({ json: { contextWindowTokens: 65536, source: 'provider' } });
  });
  await page.getByRole('button', { name: '自动获取', exact: true }).click();
  await requested.promise;
  await page.getByLabel('上下文窗口（tokens）').fill('500000');
  const detected = page.waitForResponse('**/api/settings/model/context');
  release.resolve();
  await detected;
  await expect(page.getByLabel('上下文窗口（tokens）')).toHaveValue('500000');
});
